name: release

on:
  push:
    tags:
      - '*'

env:
  MIX_ENV: prod

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.17.0]
        otp: [27.0]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Publish to Hex
      uses: synchronal/hex-publish-action@v3
      with:
        name: supabase_potion
        key: ${{ secrets.HEX_PM_KEY }}
        tag-release: true
